{"uuid": "7c69875a-f26b-4043-ae6b-5b6df113b590", "children": ["6ca2db46-25af-4aec-b3fe-3a0744b7d0c1"], "befores": [{"name": "pre_conditions", "status": "passed", "start": 1637888374524, "stop": 1637888375024}], "afters": [{"name": "pre_conditions::0", "status": "broken", "statusDetails": {"message": "TypeError: comment() takes 1 positional argument but 2 were given\n", "trace": "  File \"c:\\users\\aldo.madrid\\documents\\automationexample\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\aldo.madrid\\documents\\automationexample\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\aldo.madrid\\Documents\\AutomationExample\\Xirgo_KB1_Scripts\\Panic\\test_003_panic_and_power_loss.py\", line 17, in pre_conditions\n    Report.comment('******************Tear Down*****************', True)\n"}, "start": 1637888377045, "stop": 1637888377047}], "start": 1637888374524, "stop": 1637888377047}