{"name": "test_003_panic_and_power_loss", "status": "broken", "statusDetails": {"message": "TypeError: step() missing 1 required positional argument: 'string'", "trace": "pre_conditions = None\n\n>   ???\nE   TypeError: step() missing 1 required positional argument: 'string'\n\nC:\\Users\\aldo.madrid\\Documents\\AutomationExample\\Scripts\\Xirgo_KB1_Testing\\03_Panic\\test_003_panic_and_power_loss.py:36: TypeError"}, "attachments": [{"name": "stdout", "source": "19184eb0-47ce-4f48-b92b-fe9badb2e238-attachment.txt", "type": "text/plain"}], "start": 1637785577237, "stop": 1637785577241, "uuid": "e9b4f8a9-6ee3-4ce2-a8b8-dde6a68fa7ba", "historyId": "9b73afe4f6d784d4d0e04292f62f2a97", "testCaseId": "ad0db2d4bed47ab470477f94a5860153", "fullName": "Xirgo_KB1_Scripts.Panic.test_003_panic_and_power_loss#test_003_panic_and_power_loss", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Xirgo_KB1_Scripts.Panic"}, {"name": "suite", "value": "test_003_panic_and_power_loss"}, {"name": "host", "value": "WX-AMADRID"}, {"name": "thread", "value": "16000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Xirgo_KB1_Scripts.Panic.test_003_panic_and_power_loss"}]}