{"name": "test_003_panic_and_power_loss", "status": "passed", "attachments": [{"name": "stdout", "source": "9750357b-8227-495b-9158-5bdac23e3a69-attachment.txt", "type": "text/plain"}], "start": 1637733523088, "stop": 1637733524102, "uuid": "3c4e56b1-feb9-456d-bc05-a076a632d603", "historyId": "43bee29cbf91c5e3ec83167a5f62749f", "testCaseId": "1616fc7e4c0db1c5cf22705002a1aa85", "fullName": "Scripts.Xirgo_KB1_Testing.03_Panic.test_003_panic_and_power_loss#test_003_panic_and_power_loss", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Scripts.Xirgo_KB1_Testing.03_Panic"}, {"name": "suite", "value": "test_003_panic_and_power_loss"}, {"name": "host", "value": "WX-AMADRID"}, {"name": "thread", "value": "21104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Scripts.Xirgo_KB1_Testing.03_Panic.test_003_panic_and_power_loss"}]}